// src/routes/search/+page.svelte
<script lang="ts">
  import {
    searchAnything,
    searchPlaylists,
    searchTracks,
    searchUsers,
  } from "$lib/api/search";
  import InfiniteQueryView from "$lib/components/InfiniteQueryView.svelte";
  import Main from "$lib/components/Main.svelte";
  import SearchBar from "$lib/components/SearchBar.svelte";
  import SegmentedPicker from "$lib/components/SegmentedPicker.svelte";
  import { max_items_per_page } from "$lib/constants";
  import { match } from "$lib/utils";
  import { createInfiniteQuery } from "@tanstack/svelte-query";
  import { Debounced } from "runed";
  import { useSearchParams } from "runed/kit";
  import * as v from "valibot";

  const searchParams = useSearchParams(
    v.object({
      q: v.optional(v.string(), ""),
      kind: v.optional(
        v.picklist(["all", "tracks", "playlists", "users"]),
        "all",
      ),
    }),
    {
      noScroll: true,
      pushHistory: false,
    },
  );

  const debouncedQ = new Debounced(() => searchParams.q);

  const searchQuery = createInfiniteQuery(() => ({
    queryKey: ["search", debouncedQ.current, searchParams.kind],
    queryFn: async ({ pageParam }) => {
      if (!debouncedQ.current) return [];

      return await match(searchParams.kind, {
        tracks: () => searchTracks,
        playlists: () => searchPlaylists,
        users: () => searchUsers,
        all: () => searchAnything,
      })({
        query: debouncedQ.current,
        offset: pageParam * max_items_per_page,
        limit: max_items_per_page,
      }).then((res) => res.collection);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage, allPages) =>
      lastPage.length < max_items_per_page ? allPages.length : undefined,
  }));
</script>

<svelte:head>
  <title>results for '{debouncedQ.current}' - Cloudscape</title>
</svelte:head>

<Main>
  {#snippet left()}
    <SearchBar value={searchParams.q} />
  {/snippet}

  {#snippet right()}
    <SegmentedPicker
      options={["all", "tracks", "playlists", "users"]}
      bind:current={searchParams.kind}
    />
    <InfiniteQueryView query={searchQuery} />
  {/snippet}
</Main>

// src/routes/search.tsx
import { searchAnything, searchPlaylists, searchTracks, searchUsers } from '$lib/api/search'
import { InfiniteQueryView } from '$lib/components/InfiniteQueryView'
import { Main } from '$lib/components/Main'
import { SearchBar } from '$lib/components/SearchBar'
import { SegmentedPicker } from '$lib/components/ui/SegmentedPicker'
import { max_items_per_page } from '$lib/constants'
import { useDocumentHead } from '$lib/hooks'
import { useInfiniteQuery } from '@tanstack/react-query'
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { match } from 'matchexpr'
import { useEffect, useState } from 'react'

import * as v from 'valibot'

const kinds = ['all', 'tracks', 'playlists', 'users'] as const

export const Route = createFileRoute('/search')({
  validateSearch: v.object({
    q: v.optional(v.string(), ''),
    kind: v.optional(v.picklist(kinds), 'all'),
  }),
  component: SearchPage,
})
function SearchPage() {
  const searchParams = Route.useSearch()
  const navigate = useNavigate({ from: Route.fullPath })
  const [debouncedQ, setDebouncedQ] = useState(searchParams.q)

  useEffect(() => {
    const timeout = setTimeout(setDebouncedQ, 250, searchParams.q)
    return () => clearTimeout(timeout)
  }, [searchParams.q])

  useDocumentHead(`results for '${debouncedQ}' - Cloudscape`)

  const searchQuery = useInfiniteQuery({
    queryKey: ['search', debouncedQ, searchParams.kind],
    queryFn: async ({ pageParam }) => {
      if (!debouncedQ)
        return []

      const searchFn = match(searchParams.kind, {
        tracks: () => searchTracks,
        playlists: () => searchPlaylists,
        users: () => searchUsers,
        all: () => searchAnything,
      })

      const res = await searchFn({
        query: debouncedQ,
        offset: pageParam * max_items_per_page,
        limit: max_items_per_page,
      })

      return res.collection
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage, allPages) =>
      lastPage.length < max_items_per_page ? undefined : allPages.length,
  })

  function updateSearch(next: Partial<typeof searchParams>) {
    navigate({
      search: previous => ({ ...previous, ...next }),
      replace: true,
      resetScroll: false,
    })
  }

  return (
    <Main
      left={(
        <SearchBar key={searchParams.q} value={searchParams.q} />
      )}
      right={(
        <>
          <SegmentedPicker
            options={kinds}
            current={searchParams.kind}
            onChange={kind => updateSearch({ kind })}
          />
          <InfiniteQueryView query={searchQuery} />
        </>
      )}
    />
  )
}
