// src/lib/components/ui/segmented-picker.tsx
import { cn } from 'cnfast'
import { Button } from './button'

export function SegmentedPicker<T extends readonly string[]>({
  options,
  current,
  onChange,
  className,
}: {
  options: T
  current?: T[number]
  onChange?: (value: T[number]) => void
  className?: string
}) {
  return (
    <div className={cn('flex gap-2', className)}>
      {options.map(option => (
        <Button
          key={option}
          variant={current === option ? 'primary' : 'secondary'}
          onClick={() => onChange?.(option)}
        >
          {option}
        </Button>
      ))}
    </div>
  )
}

// src/lib/components/ui/SegmentedPicker.svelte
<script lang="ts" generics="T extends string[]">
  import Button from "./Button.svelte";
  import { cn, type ClassValue } from "cnfn";

  let {
    options,
    current = $bindable(),
    onchange,
    class: className,
  }: {
    options: T;
    current?: T[number];
    onchange?: (value: T[number]) => void;
    class?: ClassValue;
  } = $props();
</script>

<div class={cn("flex gap-2", className)}>
  {#each options as option (option)}
    {#key current}
      <Button
        variant={current === option ? "primary" : "secondary"}
        onclick={() => {
          current = option;
          onchange?.(option);
        }}
      >
        {option}
      </Button>
    {/key}
  {/each}
</div>
