// src/lib/components/infinite-query-view.tsx
import type { Playlist } from '$lib/schemas/playlist'
import type { Track } from '$lib/schemas/track'
import type { User } from '$lib/schemas/user'
import type { InfiniteData, UseInfiniteQueryResult } from '@tanstack/react-query'
import { match } from 'matchexpr'
import { useMemo } from 'react'
import { InfiniteQueryLoadMore } from './infinite-query-load-more'
import { PlaylistListing } from './listings/playlist-listing'
import { TrackListing } from './listings/track-listing'
import { UserListing } from './listings/user-listing'
import { QueryView } from './query-view'

type Result = Track | Playlist | User

export function InfiniteQueryView<T extends Result>({
  query,
  orderedIds,
}: {
  query: UseInfiniteQueryResult<InfiniteData<T[], unknown>, Error>
  orderedIds?: number[]
}) {
  const sortedPages = useMemo(() => {
    const pages = query.data?.pages ?? []
    if (!orderedIds?.length)
      return pages

    const order = new Map(orderedIds.map((id, index) => [id, index]))

    return pages.map(page => [...page].sort((a, b) => {
      const ai = order.get(a.id)
      const bi = order.get(b.id)
      if (ai === undefined && bi === undefined)
        return 0
      if (ai === undefined)
        return 1
      if (bi === undefined)
        return -1
      return ai - bi
    }))
  }, [query.data?.pages, orderedIds])

  const results = sortedPages.flat()

  const renderResult = (result: Result) => match(result, 'kind', {
    track: result => <TrackListing key={result.id} track={result} />,
    playlist: result => <PlaylistListing key={result.id} playlist={result} />,
    user: result => <UserListing key={result.id} user={result} />,
  })

  return (
    <>
      <QueryView
        query={query}
        content={() => (
          <>
            {results.length === 0 && (
              <span className='mt-4 text-lg text-base-900-100/25'>Nothing here...</span>
            )}

            {results.map(renderResult)}
          </>
        )}
      />

      <InfiniteQueryLoadMore query={query} />
    </>
  )
}

// src/lib/components/InfiniteQueryView.svelte
<script lang="ts" generics="T extends Track | Playlist | User">
  import type { Playlist } from "$lib/schemas/playlist";
  import type { Track } from "$lib/schemas/track";
  import type { User } from "$lib/schemas/user";
  import { whenInView } from "$lib/utils";
  import ErrorDisplay from "./ErrorDisplay.svelte";
  import Spinner from "./Spinner.svelte";
  import PlaylistListing from "./listings/PlaylistListing.svelte";
  import TrackListing from "./listings/TrackListing.svelte";
  import UserListing from "./listings/UserListing.svelte";
  import Button from "./ui/Button.svelte";
  import type {
    CreateInfiniteQueryResult,
    InfiniteData,
  } from "@tanstack/svelte-query";
  import { fly } from "svelte/transition";

  const {
    query,
    orderedIds,
  }: {
    query: CreateInfiniteQueryResult<InfiniteData<T[], unknown>, Error>;
    orderedIds?: number[];
  } = $props();

  const sortedPages = $derived.by(() => {
    if (!orderedIds) {
      return query.data?.pages ?? [];
    }

    return query.data?.pages.map((page) => {
      if (orderedIds.length === 0) return page;

      return page.sort((a, b) => {
        const ai = orderedIds.indexOf(a.id);
        const bi = orderedIds.indexOf(b.id);
        if (ai === -1 && bi === -1) return 0;
        if (ai === -1) return 1;
        if (bi === -1) return -1;
        return ai - bi;
      });
    });
  });
</script>

{#if query.isLoading}
  <Spinner />
{:else if query.isError}
  <ErrorDisplay error={query.error} />
{:else}
  <div in:fly={{ y: 16 }} class="flex flex-col gap-4">
    {#each sortedPages as page (page)}
      {#each page as result (result.id)}
        {#if result.kind === "track"}
          <TrackListing track={result as Track} />
        {:else if result.kind === "playlist"}
          <PlaylistListing playlist={result as Playlist} />
        {:else if result.kind === "user"}
          <UserListing user={result as User} />
        {/if}
      {/each}
    {:else}
      {#if !query.isLoading}
        <span class="mt-4 text-lg text-mist-100-900/25">Nothing here...</span>
      {/if}
    {/each}
  </div>
{/if}

{#if query.hasNextPage}
  <Button
    class="mt-8 w-full"
    onclick={() => {
      query.fetchNextPage();
    }}
    {@attach whenInView(() => {
      if (query.isFetching) return;
      query.fetchNextPage();
    })}
  >
    Load more
  </Button>
{/if}
