// src/lib/components/ListingThumbnail.svelte
<script lang="ts">
  import { cn, type ClassValue } from "cnfn";

  export interface ListingThumbnailProps {
    src?: string | null;
    alt: string;
    class?: ClassValue;
  }

  const { src, alt, ...props }: ListingThumbnailProps = $props();

  let hasFailed = $state(false);
</script>

{#if src && !hasFailed}
  <img
    {src}
    {alt}
    class={cn("aspect-square size-12 rounded", props.class)}
    onerror={() => (hasFailed = true)}
  />
{:else}
  <div class="aspect-square size-12 rounded bg-base-300-700"></div>
{/if}

// src/lib/components/ListingThumbnail.tsx
import type { ClassValue } from 'cnfn'
import { cn } from 'cnfn'
import { useState } from 'react'

export interface ListingThumbnailProps {
  src?: string | null
  alt: string
  className?: ClassValue
}

export default function ListingThumbnail({ src, alt, className }: ListingThumbnailProps) {
  const [hasFailed, setHasFailed] = useState(false)

  if (src && !hasFailed) {
    return (
      <img
        src={src}
        alt={alt}
        className={cn('aspect-square size-12 rounded-sm', className)}
        onError={() => setHasFailed(true)}
      />
    )
  }

  return <div className="aspect-square size-12 rounded-sm bg-base-300-700" />
}
