// src/lib/components/Main.tsx
import type { ClassValue } from 'cnfn'
import type { ReactNode } from 'react'
import { cn } from 'cnfn'

export default function Main({
  children,
  left,
  right,
  split = [50, 50],
  className,
}: {
  children?: ReactNode
  left?: ReactNode
  right?: ReactNode
  split?: [number, number]
  className?: ClassValue
}) {
  const [leftSplit, rightSplit] = split

  function accountForGap(percent: number) {
    return `calc(${percent}% - .5rem)`
  }

  const gridTemplateColumns
    = `${accountForGap(leftSplit)} ${accountForGap(rightSplit)}`

  return (
    <main
      className={cn(
        'mx-auto mt-16 flex max-w-5xl flex-col md:grid md:gap-4',
        className,
      )}
      style={{ gridTemplateColumns }}
    >
      {left && (
        <div className="top-16 flex h-fit flex-col gap-4 p-4 md:sticky">
          {left}
        </div>
      )}

      {right && (
        <div className="mb-64 flex flex-col gap-4 p-4">
          {right}
        </div>
      )}

      {!left && !right && children && (
        <div className="mb-64 flex flex-col gap-4 p-4">
          {children}
        </div>
      )}
    </main>
  )
}

// src/lib/components/Main.svelte
<script lang="ts">
  import { type ClassValue, cn } from "cnfn";
  import type { Snippet } from "svelte";

  const {
    children,
    left,
    right,
    split = [50, 50],
    class: className,
  }: {
    children?: Snippet;
    left?: Snippet;
    right?: Snippet;
    split?: [number, number];
    class?: ClassValue;
  } = $props();

  const [leftSplit, rightSplit] = $derived(split);

  function accountForGap(percent: number) {
    return `calc(${percent}% - .5rem)`;
  }

  const gridTemplateColumns = $derived.by(
    () => `${accountForGap(leftSplit)} ${accountForGap(rightSplit)}`,
  );
</script>

<main
  class={cn(
    "mx-auto mt-16 flex max-w-5xl flex-col md:grid md:gap-4",
    className,
  )}
  style="grid-template-columns: {gridTemplateColumns}"
>
  {#if left}
    <div class="top-16 flex h-fit flex-col gap-4 p-4 md:sticky">
      {@render left()}
    </div>
  {/if}

  {#if right}
    <div class="mb-64 flex flex-col gap-4 p-4">
      {@render right()}
    </div>
  {/if}

  {#if !left && !right && children}
    <div class="mb-64 flex flex-col gap-4 p-4">
      {@render children()}
    </div>
  {/if}
</main>
