// src/lib/components/NowPlayingView.svelte
<script lang="ts">
  import { onNavigate } from "$app/navigation";
  import { getRelatedTracks } from "$lib/api/discovery";
  import { getTrackSource } from "$lib/api/track";
  import { isPaused, nowPlaying, showNowPlayingView } from "$lib/global.svelte";
  import { Hls } from "$lib/hls";
  import type { Track } from "$lib/schemas/track";
  import Menu from "./Menu.svelte";
  import QueryView from "./QueryView.svelte";
  import TrackListing, {
    getTrackListingMenuActions,
  } from "./listings/TrackListing.svelte";
  import UserListing from "./listings/UserListing.svelte";
  import Button from "./ui/Button.svelte";
  import { XIcon } from "@lucide/svelte";
  import { createQuery } from "@tanstack/svelte-query";
  import { cn } from "cnfn";

  $effect(() => {
    if (nowPlaying.current) {
      isPaused.current = true;

      if ("mediaSession" in navigator) {
        navigator.mediaSession.metadata = new MediaMetadata({
          title: nowPlaying.current.title,
          artist: nowPlaying.current.user.username,
          album: "Cloudscape",
          artwork: [
            {
              src:
                nowPlaying.current.artwork_url?.replace("large", "t500x500") ??
                "",
              sizes: "500x500",
              type: "image/jpeg",
            },
          ],
        });
      }
    }
  });

  const applySource = (track: Track) => (element: HTMLAudioElement) => {
    getTrackSource(track.user.permalink + "/" + track.permalink).then((url) => {
      if (!Hls.isSupported()) {
        throw new Error("hls is not supported");
      }

      const hls = new Hls();
      hls.loadSource(url);
      hls.attachMedia(element);
    });
  };

  onNavigate(() => {
    showNowPlayingView.current = false;
  });

  const relatedTracksQuery = createQuery(() => ({
    queryKey: ["related", nowPlaying.current?.id],
    queryFn: async () => {
      if (!nowPlaying.current) return [];

      const relatedTracks = await getRelatedTracks(nowPlaying.current.id);

      return relatedTracks.collection;
    },
  }));
</script>

<svelte:window
  onkeydown={(e) => {
    if (e.key === "Escape") {
      e.preventDefault();
      showNowPlayingView.current = false;
    }
  }}
/>

<div
  class={cn(
    "bg-mist-300-700/75 fixed inset-x-0 z-30 grid h-full grid-cols-1 place-items-center gap-x-8 overflow-y-scroll p-4 backdrop-blur-lg transition-[top] duration-300 md:grid-cols-2",
    showNowPlayingView.current ? "top-0" : "top-full",
  )}
>
  <div class="flex w-full flex-col gap-4 max-md:mt-16 md:max-w-sm">
    {#if nowPlaying.current?.artwork_url}
      <img
        src={nowPlaying.current.artwork_url.replace("large", "t500x500")}
        class="mt-12 aspect-square w-full rounded-xl"
        alt=""
      />
    {:else}
      <div
        class="mt-12 aspect-square w-full rounded-xl bg-mist-300-700 md:max-w-md"
      ></div>
    {/if}

    {#if nowPlaying.current}
      <hgroup class="flex flex-col gap-4">
        <div class="flex items-center justify-between gap-4">
          <h1 class="text-2xl font-medium">
            {nowPlaying.current?.title}
          </h1>

          <Menu actions={getTrackListingMenuActions(nowPlaying.current)} />
        </div>

        <UserListing user={nowPlaying.current.user} />
      </hgroup>
    {/if}

    {#key nowPlaying.current}
      <audio
        class="h-10"
        bind:paused={isPaused.current}
        controls
        {@attach nowPlaying.current && applySource(nowPlaying.current)}
      >
      </audio>
    {/key}
  </div>

  <div class="mt-8 flex w-full flex-col gap-4 md:h-dvh md:max-w-sm">
    <h2 class="text-xl font-medium">Related Tracks</h2>

    <QueryView query={relatedTracksQuery}>
      {#snippet content(data)}
        {#if data.length === 0}
          <span class="text-xl font-medium text-mist-900-100/25">
            No related tracks found...
          </span>
        {:else if data}
          {#each data as track (track.id)}
            <TrackListing {track} />
          {/each}
        {/if}
      {/snippet}
    </QueryView>
  </div>

  <Button
    size="icon"
    onclick={() => (showNowPlayingView.current = false)}
    class="sticky bottom-4 max-md:mt-16 md:absolute md:top-4 md:right-4"
    icon={XIcon}
  />
</div>

// src/lib/components/now-playing-view.tsx
import type { Track } from '$lib/schemas/track'
import { getRelatedTracks } from '$lib/api/discovery'
import {
  isPausedAtom,
  nowPlayingAtom,
  selectedInstanceAtom,
  showNowPlayingViewAtom,
} from '$lib/atoms'
import { getHls } from '$lib/hls'
import { useQuery } from '@tanstack/react-query'
import { useLocation } from '@tanstack/react-router'
import { cn } from 'cnfast'
import { useAtom, useAtomValue, useSetAtom } from 'jotai'
import { XIcon } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { BlockedTrackNotice } from './blocked-track-notice'
import { TrackListing, useTrackListingMenuActions } from './listings/track-listing'
import { UserListing } from './listings/user-listing'
import { Menu } from './menu'
import { QueryView } from './query-view'
import { Button } from './ui/button'

function AudioPlayer({ track }: { track: Track }) {
  const elementRef = useRef<HTMLAudioElement>(null)
  const activeRef = useRef(true)
  const commandRef = useRef<'pause' | 'play' | null>(null)
  const selectedInstance = useAtomValue(selectedInstanceAtom)
  const [isPaused, setIsPaused] = useAtom(isPausedAtom)
  const [readySource, setReadySource] = useState<string | null>(null)
  const source = selectedInstance
    ? `${selectedInstance}/_/api/hls/${track.user.permalink}/${track.permalink}`
    : null

  useEffect(() => {
    activeRef.current = true
    return () => {
      activeRef.current = false
    }
  }, [])

  useEffect(() => {
    const element = elementRef.current
    if (!element || !source)
      return

    let hls: InstanceType<Awaited<ReturnType<typeof getHls>>> | undefined
    let cancelled = false

    void getHls().then((Hls) => {
      if (cancelled)
        return

      if (!Hls.isSupported())
        throw new Error('hls is not supported')

      hls = new Hls()
      hls.on(Hls.Events.MANIFEST_PARSED, () => {
        if (activeRef.current)
          setReadySource(source)
      })
      hls.loadSource(source)
      hls.attachMedia(element)
    })

    return () => {
      cancelled = true
      hls?.destroy()
    }
  }, [source])

  useEffect(() => {
    const element = elementRef.current
    if (!element || readySource !== source)
      return

    if (element.paused === isPaused) {
      commandRef.current = null
      return
    }

    if (isPaused) {
      commandRef.current = 'pause'
      element.pause()
    }
    else {
      commandRef.current = 'play'
      element.play().catch(() => {
        if (activeRef.current && commandRef.current === 'play') {
          commandRef.current = null
          setIsPaused(true)
        }
      })
    }
  }, [isPaused, readySource, setIsPaused, source])

  return (
    <audio
      ref={elementRef}
      className='h-10'
      controls
      onPlay={() => {
        if (commandRef.current === 'play') {
          commandRef.current = null
          return
        }
        if (commandRef.current !== 'pause')
          setIsPaused(false)
      }}
      onPause={() => {
        if (commandRef.current === 'pause') {
          commandRef.current = null
          return
        }
        if (commandRef.current !== 'play')
          setIsPaused(true)
      }}
    />
  )
}

function NowPlayingMenu({ track }: { track: Track }) {
  const actions = useTrackListingMenuActions(track)
  return <Menu actions={actions} />
}

export function NowPlayingView() {
  const location = useLocation()
  const nowPlaying = useAtomValue(nowPlayingAtom)
  const showNowPlayingView = useAtomValue(showNowPlayingViewAtom)
  const setShowNowPlayingView = useSetAtom(showNowPlayingViewAtom)
  const isBlocked = nowPlaying?.policy === 'BLOCK'

  useEffect(() => {
    if (nowPlaying) {
      if ('mediaSession' in navigator && 'MediaMetadata' in window) {
        navigator.mediaSession.metadata = new MediaMetadata({
          title: nowPlaying.title,
          artist: nowPlaying.user.username,
          album: 'Cloudscape',
          artwork: [
            {
              src: nowPlaying.artwork_url?.replace('large', 't500x500') ?? '',
              sizes: '500x500',
              type: 'image/jpeg',
            },
          ],
        })
      }
    }
  }, [nowPlaying])

  useEffect(() => {
    setShowNowPlayingView(false)
  }, [location.pathname, setShowNowPlayingView])

  useEffect(() => {
    function onKeyDown(event: KeyboardEvent) {
      if (event.key === 'Escape') {
        event.preventDefault()
        setShowNowPlayingView(false)
      }
    }

    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [setShowNowPlayingView])

  const relatedTracksQuery = useQuery({
    queryKey: ['related', nowPlaying?.id],
    queryFn: async () => {
      if (!nowPlaying)
        return []

      const relatedTracks = await getRelatedTracks(nowPlaying.id)

      return relatedTracks.collection
    },
  })

  return (
    <div
      className={cn(
        'fixed inset-0 z-30 grid grid-cols-1 place-items-center gap-x-8 overflow-y-scroll bg-base-300-700/75 p-4 backdrop-blur-lg transition-[translate,opacity] duration-300 ease-drawer will-change-[translate,opacity] motion-reduce:translate-y-0 motion-reduce:duration-200 motion-reduce:ease-out md:grid-cols-2',
        showNowPlayingView
          ? 'translate-y-0 opacity-100'
          : 'pointer-events-none translate-y-full opacity-0',
      )}
    >
      <div className='flex w-full flex-col gap-4 max-md:mt-16 md:max-w-sm'>
        {nowPlaying?.artwork_url
          ? (
              <img
                src={nowPlaying.artwork_url.replace('large', 't500x500')}
                width='500'
                height='500'
                className='mt-12 aspect-square w-full rounded-xl'
                alt=''
              />
            )
          : (
              <div
                className='mt-12 aspect-square w-full rounded-xl bg-base-300-700 md:max-w-md'
              />
            )}

        {nowPlaying && (
          <hgroup className='flex flex-col gap-4'>
            <div className='flex items-center justify-between gap-4'>
              <h1 className='text-2xl font-medium'>
                {nowPlaying.title}
              </h1>

              <NowPlayingMenu track={nowPlaying} />
            </div>

            <UserListing user={nowPlaying.user} />
          </hgroup>
        )}

        {isBlocked
          ? <BlockedTrackNotice />
          : nowPlaying && <AudioPlayer key={nowPlaying.id} track={nowPlaying} />}
      </div>

      <div className='mt-8 flex w-full flex-col gap-4 md:h-dvh md:max-w-sm'>
        <h2 className='text-xl font-medium'>Related Tracks</h2>

        <QueryView
          query={relatedTracksQuery}
          content={data => data.length === 0
            ? (
                <span className='text-xl font-medium text-base-900-100/25'>
                  No related tracks found...
                </span>
              )
            : data.map(track => <TrackListing key={track.id} track={track} />)}
        />
      </div>

      <Button
        size='icon'
        onClick={() => setShowNowPlayingView(false)}
        className='sticky bottom-4 max-md:mt-16 md:absolute md:top-4 md:right-4'
        icon={XIcon}
      />
    </div>
  )
}
