// src/lib/components/now-playing-bar.tsx
import { isPausedAtom, nowPlayingAtom, showNowPlayingViewAtom } from '$lib/atoms'
import { hapticTrigger } from 'ios-haptics'
import { useAtom, useAtomValue, useSetAtom } from 'jotai'
import { PauseIcon, PlayIcon } from 'lucide-react'
import { AnimatePresence, motion, useReducedMotion } from 'motion/react'
import { ListingThumbnail } from './listing-thumbnail'
import { Button } from './ui/button'

export function NowPlayingBar() {
  const nowPlaying = useAtomValue(nowPlayingAtom)
  const showNowPlayingView = useAtomValue(showNowPlayingViewAtom)
  const setShowNowPlayingView = useSetAtom(showNowPlayingViewAtom)
  const [isPaused, setIsPaused] = useAtom(isPausedAtom)
  const reduceMotion = useReducedMotion()
  const StatusIcon = isPaused ? PlayIcon : PauseIcon
  const isBlocked = nowPlaying?.policy === 'BLOCK'

  return (
    <AnimatePresence>
      {!showNowPlayingView && (
        <motion.div
          initial={{ y: reduceMotion ? 0 : 100, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          exit={{ y: reduceMotion ? 0 : 100, opacity: 0 }}
          transition={{ duration: 0.2 }}
          className='fixed inset-x-2 bottom-2 z-30 mx-auto rounded-2xl bg-base-300-700/75 backdrop-blur-lg md:inset-x-4 md:bottom-4 md:max-w-xl'
        >
          <div className='grid grid-cols-[1fr_auto] items-center gap-4 p-3'>
            <button
              onClick={() => setShowNowPlayingView(true)}
              className='flex gap-4 truncate text-left'
            >
              <div className='relative size-12 shrink-0 overflow-hidden rounded-sm'>
                <AnimatePresence>
                  {nowPlaying && (
                    <motion.div
                      key={nowPlaying.id}
                      transition={reduceMotion
                        ? { duration: 0.15 }
                        : { ease: 'easeInOut', duration: 0.2 }}
                      className='absolute inset-0'
                      initial={reduceMotion
                        ? { opacity: 0 }
                        : { scale: 0.96, filter: 'blur(2px)', opacity: 0 }}
                      animate={reduceMotion
                        ? { opacity: 1 }
                        : { scale: 1, filter: 'blur(0px)', opacity: 1 }}
                      exit={reduceMotion
                        ? { opacity: 0 }
                        : { scale: 0.96, filter: 'blur(2px)', opacity: 0 }}
                    >
                      <ListingThumbnail
                        src={nowPlaying.artwork_url}
                        alt=''
                      />
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>

              <div className='flex w-full min-w-0 flex-col'>
                <h3 className='m-0 truncate p-0'>
                  {nowPlaying?.title ?? ''}
                </h3>
                <p className='truncate opacity-50'>
                  {nowPlaying?.user.username ?? ''}
                </p>
              </div>
            </button>

            <Button
              ref={isBlocked ? undefined : hapticTrigger}
              size='icon'
              disabled={isBlocked}
              onClick={() => setIsPaused(prev => !prev)}
            >
              <motion.div
                key={String(isPaused)}
                transition={reduceMotion
                  ? { duration: 0.15 }
                  : { type: 'spring', duration: 0.3, bounce: 0 }}
                initial={reduceMotion
                  ? { opacity: 0 }
                  : { rotate: 180, scale: 0.95, filter: 'blur(2px)' }}
                animate={reduceMotion
                  ? { opacity: 1 }
                  : isPaused
                    ? { rotate: 360, scale: 1, filter: 'blur(0px)' }
                    : { rotate: 180, scale: 1, filter: 'blur(0px)' }}
              >
                <StatusIcon fill='currentColor' size={16} />
              </motion.div>
            </Button>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}

// src/lib/components/NowPlayingBar.svelte
<script lang="ts">
  import { isPaused, nowPlaying, showNowPlayingView } from "$lib/global.svelte";
  import ListingThumbnail from "./ListingThumbnail.svelte";
  import Button from "./ui/Button.svelte";
  import { AnimatePresence, motion } from "@humanspeak/svelte-motion";
  import { PauseIcon, PlayIcon } from "@lucide/svelte";
  import NumericText from "@numeric-text/svelte";
  import { fly } from "svelte/transition";

  const StatusIcon = $derived(isPaused.current ? PlayIcon : PauseIcon);
</script>

{#if !showNowPlayingView.current}
  <div
    in:fly={{ y: 100 }}
    class="fixed inset-x-2 bottom-2 z-30 mx-auto rounded-2xl bg-base-300-700/75 backdrop-blur-lg md:inset-x-4 md:bottom-4 md:max-w-xl"
  >
    <div class="grid grid-cols-[1fr_auto] items-center gap-4 p-3">
      <button
        onclick={() => (showNowPlayingView.current = true)}
        class="flex gap-4 truncate text-left"
      >
        <AnimatePresence>
          {#key nowPlaying.current?.artwork_url}
            <motion.div
              key={nowPlaying.current!.artwork_url!}
              transition={{ ease: "easeInOut" }}
              class="aspect-square size-12 rounded"
              initial={{
                scale: 0.5,
                filter: "blur(4px)",
                rotate: 15,
                opacity: 0,
              }}
              animate={{
                scale: 1,
                filter: "blur(0px)",
                rotate: 0,
                opacity: 1,
              }}
              exit={{
                scale: 0.5,
                filter: "blur(10px)",
                rotate: -15,
                opacity: 0,
              }}
            >
              <ListingThumbnail src={nowPlaying.current?.artwork_url} alt="" />
            </motion.div>
          {/key}
        </AnimatePresence>

        <div class="flex w-full min-w-0 flex-col">
          <h3 class="truncate m-0 p-0">
            <NumericText
              class="inline-block"
              value={nowPlaying.current!.title}
            />
          </h3>
          <p class="truncate opacity-50">
            <NumericText
              class="inline-block"
              value={nowPlaying.current!.user.username}
            />
          </p>
        </div>
      </button>

      <Button
        size="icon"
        onclick={() => {
          isPaused.current = !isPaused.current;
        }}
      >
        <motion.div
          initial={{
            rotate: 180,
            scale: 0,
            filter: "blur(10px)",
          }}
          animate={isPaused.current
            ? { rotate: 360, scale: 1, filter: "blur(0px)" }
            : { rotate: 180, scale: 1, filter: "blur(0px)" }}
        >
          <StatusIcon fill="currentColor" size={16} />
        </motion.div>
      </Button>
    </div>
  </div>
{/if}
