// src/lib/components/QueryView.svelte
<script lang='ts' generics="T">
  import type { CreateQueryResult } from '@tanstack/svelte-query'
  import type { ClassValue } from 'cnfn'
  import type { Snippet } from 'svelte'
  import Spinner from '$lib/components/Spinner.svelte'
  import { cn } from 'cnfn'
  import { cubicOut } from 'svelte/easing'
  import { MediaQuery } from 'svelte/reactivity'
  import { fly } from 'svelte/transition'
  import ErrorDisplay from './ErrorDisplay.svelte'

  const {
    query,
    content,
    class: className,
  }: {
    query: CreateQueryResult<T>
    content: Snippet<[data: T]>
    class?: ClassValue
  } = $props()

  const reduceMotion = new MediaQuery('(prefers-reduced-motion: reduce)')
</script>

{#if query.isLoading}
  <Spinner />
{:else if query.isError}
  <ErrorDisplay error={query.error} />
{:else if query.data}
  <div
    in:fly={{ y: reduceMotion.current ? 0 : 16, duration: 200, easing: cubicOut }}
    class={cn('flex flex-col gap-4', className)}
  >
    {@render content(query.data)}
  </div>
{/if}

// src/lib/components/query-view.tsx
import type { UseInfiniteQueryResult, UseQueryResult } from '@tanstack/react-query'
import type { ReactNode } from 'react'
import { cn } from 'cnfast'
import { motion, useReducedMotion } from 'motion/react'
import { ErrorDisplay } from './error-display'
import { Spinner } from './spinner'

export function QueryView<T>({
  query,
  content,
  className,
}: {
  query: UseQueryResult<T> | UseInfiniteQueryResult<T>
  content: (data: T) => ReactNode
  className?: string
}) {
  const reduceMotion = useReducedMotion()

  if (query.isLoading)
    return <Spinner />

  if (query.isError)
    return <ErrorDisplay error={query.error} />

  return (
    <motion.div
      initial={{ y: reduceMotion ? 0 : 16, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      transition={{ duration: 0.2, ease: 'easeOut' }}
      className={cn('flex flex-col gap-4', className)}
    >
      {content(query.data!)}
    </motion.div>
  )
}
