// src/lib/components/QueryView.tsx
import type { UseQueryResult } from '@tanstack/react-query'
import type { ClassValue } from 'cnfn'
import type { ReactNode } from 'react'
import { cn } from 'cnfn'
import { motion } from 'motion/react'
import ErrorDisplay from './ErrorDisplay'
import Spinner from './Spinner'

export default function QueryView<T>({
  query,
  children,
  className,
}: {
  query: UseQueryResult<T>
  children: (data: T) => ReactNode
  className?: ClassValue
}) {
  if (query.isLoading) {
    return <Spinner />
  }

  if (query.isError) {
    return <ErrorDisplay error={query.error} />
  }

  if (query.data) {
    return (
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        className={cn('flex flex-col gap-4', className)}
      >
        {children(query.data)}
      </motion.div>
    )
  }

  return null
}

// src/lib/components/QueryView.svelte
<script lang="ts" generics="T">
  import Spinner from "$lib/components/Spinner.svelte";
  import ErrorDisplay from "./ErrorDisplay.svelte";
  import type { CreateQueryResult } from "@tanstack/svelte-query";
  import { cn, type ClassValue } from "cnfn";
  import type { Snippet } from "svelte";
  import { fly } from "svelte/transition";

  const {
    query,
    content,
    class: className,
    isLoading = (q) => q.isLoading,
  }: {
    query: CreateQueryResult<T>;
    content: Snippet<[data: T]>;
    class?: ClassValue;
    isLoading?: (query: CreateQueryResult<T>) => boolean;
  } = $props();
</script>

{#if isLoading(query)}
  <Spinner />
{:else if query.isError}
  <ErrorDisplay error={query.error} />
{:else if query.data}
  <div in:fly={{ y: 16 }} class={cn("flex flex-col gap-4", className)}>
    {@render content(query.data)}
  </div>
{/if}
