// src/lib/components/SearchBar.svelte
<script lang="ts">
  import Input from "./ui/Input.svelte";
  import { SearchIcon } from "@lucide/svelte";

  let { value = $bindable() }: { value?: string } = $props();
</script>

<form action="/search" class="w-full">
  <Input
    type="text"
    name="q"
    placeholder="Search for artists, tracks or playlists..."
    class="w-full"
    id="search-input"
    icon={SearchIcon}
    bind:value
  />
</form>

// src/lib/components/SearchBar.tsx
import { SearchIcon } from 'lucide-react'
import { useState } from 'react'
import Input from './ui/Input'

export default function SearchBar({ value = '' }: { value?: string }) {
  const [currentValue, setCurrentValue] = useState(value)

  return (
    <form action="/search" className="w-full">
      <Input
        type="text"
        name="q"
        placeholder="Search for artists, tracks or playlists..."
        className="w-full"
        id="search-input"
        icon={SearchIcon}
        value={currentValue}
        onValueChange={setCurrentValue}
      />
    </form>
  )
}
