// src/routes/_/preferences/theme/+page.svelte
<script lang="ts">
  import Button from "$lib/components/ui/Button.svelte";
  import {
    isBlackAccent,
    selectedAccentColor,
    selectedBaseColor,
  } from "$lib/global.svelte";
  import { accentColors, baseColors, type ValidColor } from "$lib/theme";
  import { match } from "$lib/utils";
  import { setMode, userPrefersMode } from "mode-watcher";

  const themeModes = ["light", "dark", "system"] as const;
</script>

{#snippet swatch(
  color: ValidColor,
  {
    isSelected,
    onclick,
  }: {
    isSelected: boolean;
    onclick: VoidFunction;
  },
)}
  {@const style = match(color, {
    black: () => "--swatch-color-light: #000; --swatch-color-dark: #fff;",
    _: () => `
      --swatch-color-light: var(--color-${color}-500, var(--color-${color}));
      --swatch-color-dark: var(--color-${color}-400, var(--color-${color}));
    `,
  })}
  <Button {style} {onclick} variant={isSelected ? "primary" : "secondary"}>
    <div
      class="size-3 rounded-full bg-(--swatch-color-light) outline-2 outline-base-300-700 dark:bg-(--swatch-color-dark)"
    ></div>
    {color}
  </Button>
{/snippet}

<h3 class="text-xl font-medium">Theme</h3>

<span>Mode</span>

<div class="flex flex-wrap gap-2">
  {#each themeModes as themeMode (themeMode)}
    {@const isSelected = userPrefersMode.current === themeMode}
    <Button
      variant={isSelected ? "primary" : "secondary"}
      onclick={() => setMode(themeMode)}
      class="capitalize"
    >
      {themeMode}
    </Button>
  {/each}
</div>

<span>Accent Colors</span>

<div class="flex flex-wrap gap-2">
  {@render swatch("black", {
    isSelected: isBlackAccent.current === true,
    onclick: () => {
      isBlackAccent.current = !isBlackAccent.current;
    },
  })}

  {#each accentColors as accentColor (accentColor)}
    {@render swatch(accentColor, {
      isSelected:
        selectedAccentColor.current === accentColor && !isBlackAccent.current,
      onclick: () => {
        isBlackAccent.current = false;
        selectedAccentColor.current = accentColor;
      },
    })}
  {/each}
</div>

<span>Base Colors</span>

<div class="flex flex-wrap gap-2">
  {#each baseColors as baseColor (baseColor)}
    {@render swatch(baseColor, {
      isSelected: selectedBaseColor.current === baseColor,
      onclick: () => {
        selectedBaseColor.current = baseColor;
      },
    })}
  {/each}
</div>

// src/routes/[_]/preferences/theme/index.tsx
import type { ValidColor } from '$lib/theme'
import type { CSSProperties } from 'react'
import Button from '$lib/components/ui/Button'
import {
  isBlackAccentAtom,
  selectedAccentColorAtom,
  selectedBaseColorAtom,
  themeModeAtom,
} from '$lib/global'
import { accentColors, baseColors } from '$lib/theme'
import { match } from '$lib/utils/match'
import { createFileRoute } from '@tanstack/react-router'
import { useAtom } from 'jotai'

const themeModes = ['light', 'dark', 'system'] as const

export const Route = createFileRoute('/_/preferences/theme/')({
  component: ThemePage,
})

function ThemePage() {
  const [themeMode, setThemeMode] = useAtom(themeModeAtom)
  const [isBlackAccent, setIsBlackAccent] = useAtom(isBlackAccentAtom)
  const [selectedAccentColor, setSelectedAccentColor] = useAtom(selectedAccentColorAtom)
  const [selectedBaseColor, setSelectedBaseColor] = useAtom(selectedBaseColorAtom)

  return (
    <>
      <h3 className="text-xl font-medium">Theme</h3>

      <span>Mode</span>

      <div className="flex flex-wrap gap-2">
        {themeModes.map(themeModeOption => (
          <Button
            key={themeModeOption}
            variant={themeMode === themeModeOption ? 'primary' : 'secondary'}
            onClick={() => setThemeMode(themeModeOption)}
            className="capitalize"
          >
            {themeModeOption}
          </Button>
        ))}
      </div>

      <span>Accent Colors</span>

      <div className="flex flex-wrap gap-2">
        <Swatch
          color="black"
          isSelected={isBlackAccent === true}
          onClick={() => {
            setIsBlackAccent(!isBlackAccent)
          }}
        />

        {accentColors.map(accentColor => (
          <Swatch
            key={accentColor}
            color={accentColor}
            isSelected={selectedAccentColor === accentColor && !isBlackAccent}
            onClick={() => {
              setIsBlackAccent(false)
              setSelectedAccentColor(accentColor)
            }}
          />
        ))}
      </div>

      <span>Base Colors</span>

      <div className="flex flex-wrap gap-2">
        {baseColors.map(baseColor => (
          <Swatch
            key={baseColor}
            color={baseColor}
            isSelected={selectedBaseColor === baseColor}
            onClick={() => {
              setSelectedBaseColor(baseColor)
            }}
          />
        ))}
      </div>
    </>
  )
}

function Swatch({
  color,
  isSelected,
  onClick,
}: {
  color: ValidColor
  isSelected: boolean
  onClick: VoidFunction
}) {
  const style = match(color, {
    black: () => ({
      '--swatch-color-light': '#000',
      '--swatch-color-dark': '#fff',
    }),
    _: (): CSSProperties => ({
      '--swatch-color-light': `var(--color-${color}-500, var(--color-${color}))`,
      '--swatch-color-dark': `var(--color-${color}-400, var(--color-${color}))`,
    } as CSSProperties),
  }) as CSSProperties

  return (
    <Button style={style} onClick={onClick} variant={isSelected ? 'primary' : 'secondary'}>
      <div className="size-3 rounded-full bg-(--swatch-color-light) outline-2 outline-base-300-700 dark:bg-(--swatch-color-dark)" />
      {color}
    </Button>
  )
}
