// src/lib/components/listings/GenericListing.svelte
<script module lang='ts'>
  import type { LucideIcon } from '@lucide/svelte'
  import type { ButtonRootProps } from 'bits-ui'
  import type { MergeExclusive } from 'type-fest'
  import type { ListingThumbnailProps } from '../ListingThumbnail.svelte'

  export type Action = MergeExclusive<
    {
      label: string
      icon: LucideIcon
      onclick: VoidFunction
    },
    {
      label: string
      icon: LucideIcon
      href: string
    }
  >

  export type GenericListingProps = ButtonRootProps & {
    title: string
    badges?: (string | false)[]
    subtitle: string
    thumbnail: ListingThumbnailProps
    actions?: Action[]
  }
</script>

<script lang='ts'>
  import { Button as BitsUiButton } from 'bits-ui'
  import ListingThumbnail from '../ListingThumbnail.svelte'
  import Menu from '../Menu.svelte'
  import Badge from '../ui/Badge.svelte'

  const {
    title,
    badges,
    subtitle,
    thumbnail,
    actions,
    disabled,
    ...props
  }: GenericListingProps = $props()
</script>

<div class='flex items-center gap-4 text-left'>
  <BitsUiButton.Root
    {...props}
    {disabled}
    class={[
      'relative isolate flex w-full min-w-0 gap-4 text-left transition-transform duration-150 ease-out',
      disabled
        ? 'cursor-not-allowed opacity-50'
        : 'cursor-pointer active:scale-97 active:opacity-50',
      'rounded-lg outline-none before:absolute before:-inset-2 before:-z-10 before:rounded-xl before:bg-base-300-700/80 before:content-[\'\'] focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-4 focus-visible:ring-offset-base-200-800',
      'before:scale-95 before:opacity-0 before:transition-[opacity,scale] before:duration-160 before:ease-out [@media(hover:hover)_and_(pointer:fine)]:hover:before:scale-100 [@media(hover:hover)_and_(pointer:fine)]:hover:before:opacity-100',
      disabled && 'before:hidden',
    ]}
  >
    <ListingThumbnail {...thumbnail} />

    <div class='flex flex-col truncate'>
      <div class='flex gap-2'>
        <h3 class='truncate'>{title}</h3>

        {#each badges as badge (badge)}
          {#if badge}
            <Badge label={badge} />
          {/if}
        {/each}
      </div>
      <p class='truncate text-accent/75'>
        {subtitle}
      </p>
    </div>
  </BitsUiButton.Root>

  {#if actions}
    <Menu {actions} {title} {subtitle} />
  {/if}
</div>

// src/lib/components/listings/generic-listing.tsx
import type { ComponentProps } from 'react'
import type { ListingThumbnailProps } from '../listing-thumbnail'
import type { Action } from '../menu'
import { Button as BaseButton } from '@base-ui/react/button'
import { Link } from '@tanstack/react-router'
import { ListingThumbnail } from '../listing-thumbnail'
import { Menu } from '../menu'
import { Badge } from '../ui/badge'

export type GenericListingProps = Omit<ComponentProps<typeof BaseButton>, 'className'> & {
  title: string
  badges?: (string | false)[]
  subtitle: string
  thumbnail: ListingThumbnailProps
  actions?: Action[]
  href?: string
}

export function GenericListing({
  title,
  badges,
  subtitle,
  thumbnail,
  actions,
  disabled,
  href,
  ...props
}: GenericListingProps) {
  const render = href ? <Link to={href} /> : undefined

  return (
    <div className='flex items-center gap-4 text-left'>
      <BaseButton
        render={render}
        nativeButton={!render}
        {...props}
        disabled={disabled}
        className={[
          'relative isolate flex w-full min-w-0 gap-4 text-left transition-transform duration-150 ease-out',
          disabled
            ? 'cursor-not-allowed opacity-50'
            : 'cursor-pointer active:scale-97 active:opacity-50',
          'before:absolute before:-inset-2 before:-z-10 before:rounded-[10px] before:bg-base-300-700 before:content-[\'\']',
          'before:scale-95 before:opacity-0 before:transition-[opacity,scale] before:duration-160 before:ease-out [@media(hover:hover)_and_(pointer:fine)]:hover:before:scale-100 [@media(hover:hover)_and_(pointer:fine)]:hover:before:opacity-100',
          disabled && 'before:hidden',
        ].filter(Boolean).join(' ')}
      >
        <ListingThumbnail {...thumbnail} />

        <div className='flex flex-col truncate'>
          <div className='flex gap-2'>
            <h3 className='truncate'>{title}</h3>

            {badges?.map(badge => badge && <Badge key={badge} label={badge} />)}
          </div>
          <p className='truncate text-accent/75'>
            {subtitle}
          </p>
        </div>
      </BaseButton>

      {actions && (
        <Menu
          actions={actions}
          title={title}
          subtitle={subtitle}
        />
      )}
    </div>
  )
}
