// src/lib/components/listings/GenericListing.tsx
import type { ButtonHTMLAttributes } from 'react'
import type { ListingThumbnailProps } from '../ListingThumbnail'
import type { Action } from '../Menu'
import { AppLink } from '$lib/router-link'
import ListingThumbnail from '../ListingThumbnail'
import Menu from '../Menu'
import Badge from '../ui/Badge'

export type GenericListingProps = Omit<
  ButtonHTMLAttributes<HTMLButtonElement>,
  'className' | 'title'
> & {
  title: string
  badges?: (string | false | undefined)[]
  subtitle: string
  thumbnail: ListingThumbnailProps
  actions?: Action[]
  href?: string
}

const listingClassName = [
  'relative isolate flex w-full min-w-0 cursor-pointer gap-4 text-left transition-transform active:scale-95 active:opacity-50',
  'before:absolute before:-inset-2 before:-z-10 before:rounded-[10px] before:bg-base-300-700 before:content-[\'\']',
  'before:scale-90 before:opacity-0 before:transition-[opacity,scale] hover:before:scale-100 hover:before:opacity-100',
].join(' ')

export default function GenericListing({
  title,
  badges = [],
  subtitle,
  thumbnail,
  actions,
  href,
  ...props
}: GenericListingProps) {
  const content = (
    <>
      <ListingThumbnail {...thumbnail} />

      <div className="flex flex-col truncate">
        <div className="flex gap-2">
          <h3 className="truncate">{title}</h3>

          {badges.map(badge => (
            badge ? <Badge key={badge} label={badge} /> : null
          ))}
        </div>
        <p className="truncate text-accent/75">
          {subtitle}
        </p>
      </div>
    </>
  )

  return (
    <div className="flex items-center gap-4 text-left">
      {href
        ? (
            <AppLink href={href} className={listingClassName}>
              {content}
            </AppLink>
          )
        : (
            <button type="button" {...props} className={listingClassName}>
              {content}
            </button>
          )}

      {actions && <Menu actions={actions} title={title} subtitle={subtitle} />}
    </div>
  )
}

// src/lib/components/listings/GenericListing.svelte
<script module lang="ts">
  import type { ListingThumbnailProps } from "../ListingThumbnail.svelte";
  import type { LucideProps } from "@lucide/svelte";
  import type { ButtonRootProps } from "bits-ui";
  import type { Component } from "svelte";
  import type { MergeExclusive } from "type-fest";

  export type Action = MergeExclusive<
    {
      label: string;
      icon: Component<LucideProps>;
      onclick: VoidFunction;
    },
    {
      label: string;
      icon: Component<LucideProps>;
      href: string;
    }
  >;

  export type GenericListingProps = ButtonRootProps & {
    title: string;
    badges?: (string | false)[];
    subtitle: string;
    thumbnail: ListingThumbnailProps;
    actions?: Action[];
  };
</script>

<script lang="ts">
  import ListingThumbnail from "../ListingThumbnail.svelte";
  import Menu from "../Menu.svelte";
  import Badge from "../ui/Badge.svelte";
  import { Button as BitsUiButton } from "bits-ui";

  const {
    title,
    badges,
    subtitle,
    thumbnail,
    actions,
    ...props
  }: GenericListingProps = $props();
</script>

<div class="flex items-center gap-4 text-left">
  <BitsUiButton.Root
    {...props}
    class={[
      "flex w-full min-w-0 isolate cursor-pointer gap-4 text-left relative transition-transform active:scale-95 active:opacity-50",
      "before:-z-10 before:content-[''] before:absolute before:-inset-2 before:rounded-[10px] before:bg-base-300-700",
      "before:opacity-0 hover:before:opacity-100 before:transition-[opacity,scale] before:scale-90 hover:before:scale-100",
    ]}
  >
    <ListingThumbnail {...thumbnail} />

    <div class="flex flex-col truncate">
      <div class="flex gap-2">
        <h3 class="truncate">{title}</h3>

        {#each badges as badge (badge)}
          {#if badge}
            <Badge label={badge} />
          {/if}
        {/each}
      </div>
      <p class="truncate text-accent/75">
        {subtitle}
      </p>
    </div>
  </BitsUiButton.Root>

  {#if actions}
    <Menu {actions} {title} {subtitle} />
  {/if}
</div>
