// src/lib/components/listings/TrackListing.svelte
<script module lang='ts'>
  import { resolve } from '$app/paths'
  import { page } from '$app/state'
  import { favoriteTrackIds } from '$lib/global.svelte'
  import { ClipboardIcon, DiscIcon, SpeakerIcon, StarIcon, StarOffIcon, UserIcon } from '@lucide/svelte'

  export function getTrackListingMenuActions(track: Track) {
    const isFavorited = favoriteTrackIds.current.includes(track.id)

    return [
      {
        label: isFavorited ? 'Unfavorite' : 'Favorite',
        icon: isFavorited ? StarOffIcon : StarIcon,
        onclick: () => {
          if (favoriteTrackIds.current.includes(track.id)) {
            favoriteTrackIds.current = favoriteTrackIds.current.filter(
              id => id !== track.id,
            )
          }
          else {
            favoriteTrackIds.current.push(track.id)
          }
        },
      },

      ...(page.route.id !== '/[user]/[track]'
        ? [
          {
            label: 'Go to track',
            icon: DiscIcon,
            href: resolve('/[user]/[track]', {
              user: track.user.permalink,
              track: track.permalink,
            }),
          },
        ]
        : []),

      ...(page.route.id !== '/[user]'
        ? [
          {
            label: 'Go to artist',
            icon: UserIcon,
            href: resolve('/[user]', {
              user: track.user.permalink,
            }),
          },
        ]
        : []),

      ...(!page.url.pathname.includes(`track-stations:${track.id}`)
        ? [
          {
            label: `Go to track station`,
            href: resolve('/[user]/sets/[playlist]', {
              user: 'discover',
              playlist: `track-stations:${track.id}`,
            }),
            icon: SpeakerIcon,
          },
        ]
        : []),

      {
        label: 'Copy track URL',
        icon: ClipboardIcon,
        onclick: () => {
          const url = `${page.url.protocol}//${page.url.host}/${track.user.permalink}/${track.permalink}`
          navigator.clipboard?.writeText(url)
        },
      },
    ]
  }
</script>

<script lang='ts'>
  import type { Track } from '$lib/schemas/track'
  import { isPaused, nowPlaying } from '$lib/global.svelte'
  import GenericListing from './GenericListing.svelte'

  const { track }: { track: Track } = $props()

  const isBlocked = $derived(track.policy === 'BLOCK')
</script>

<GenericListing
  title={track.title}
  subtitle={track.user.username}
  thumbnail={{
    src: track.artwork_url,
    alt: `Album cover of ${track.title}`,
  }}
  disabled={isBlocked}
  onclick={() => {
    nowPlaying.current = track

    if (!isBlocked) {
      setTimeout(() => {
        isPaused.current = false
      }, 50)
    }
  }}
  badges={track.policy === 'SNIP' ? ['30s only'] : []}
  actions={getTrackListingMenuActions(track)}
/>

// src/lib/components/listings/TrackListing.tsx
import type { Track } from '$lib/schemas/track'
import type { Action } from '../Menu'
import {
  favoriteTrackIdsAtom,
  isPausedAtom,
  nowPlayingAtom,
} from '$lib/global'
import { useLocation } from '@tanstack/react-router'
import { useAtomValue, useSetAtom } from 'jotai'
import { ClipboardIcon, DiscIcon, SpeakerIcon, StarIcon, StarOffIcon, UserIcon } from 'lucide-react'
import GenericListing from './GenericListing'

export function useTrackListingMenuActions(track: Track) {
  const location = useLocation()
  const favoriteTrackIds = useAtomValue(favoriteTrackIdsAtom)
  const setFavoriteTrackIds = useSetAtom(favoriteTrackIdsAtom)
  const isFavorited = favoriteTrackIds.includes(track.id)

  return [
    {
      label: isFavorited ? 'Unfavorite' : 'Favorite',
      icon: isFavorited ? StarOffIcon : StarIcon,
      onClick: () => {
        setFavoriteTrackIds((ids) => {
          if (ids.includes(track.id)) {
            return ids.filter(
              id => id !== track.id,
            )
          }

          return [...ids, track.id]
        })
      },
    },

    ...(location.pathname !== `/${track.user.permalink}/${track.permalink}`
      ? [
          {
            label: 'Go to track',
            icon: DiscIcon,
            href: `/${track.user.permalink}/${track.permalink}`,
          },
        ]
      : []),

    ...(location.pathname !== `/${track.user.permalink}`
      ? [
          {
            label: 'Go to artist',
            icon: UserIcon,
            href: `/${track.user.permalink}`,
          },
        ]
      : []),

    ...(!location.pathname.includes(`track-stations:${track.id}`)
      ? [
          {
            label: `Go to track station`,
            href: `/discover/sets/track-stations:${track.id}`,
            icon: SpeakerIcon,
          },
        ]
      : []),

    {
      label: 'Copy track URL',
      icon: ClipboardIcon,
      onClick: () => {
        const url = `${window.location.protocol}//${window.location.host}/${track.user.permalink}/${track.permalink}`
        navigator.clipboard?.writeText(url)
      },
    },
  ] satisfies Action[]
}

export default function TrackListing({ track }: { track: Track }) {
  const setNowPlaying = useSetAtom(nowPlayingAtom)
  const setIsPaused = useSetAtom(isPausedAtom)
  const isBlocked = track.policy === 'BLOCK'

  return (
    <GenericListing
      title={track.title}
      subtitle={track.user.username}
      thumbnail={{
        src: track.artwork_url,
        alt: `Album cover of ${track.title}`,
      }}
      disabled={isBlocked}
      onClick={() => {
        setNowPlaying(track)
        setIsPaused(isBlocked)
      }}
      badges={track.policy === 'SNIP' ? ['30s only'] : []}
      actions={useTrackListingMenuActions(track)}
    />
  )
}
